apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 605328093202.dkr.ecr.ap-south-1.amazonaws.com/my-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
